# External Plural Effect

This notebook investigates the external plural effect (ExtPE) in German compounding as defined by Schäfer & Pankratz 2018:

> A plural on the entire compound (formally on the head constituent) might trigger the use of a pluralic linking element. We call this the external plural effect.


## Background

Schäfer & Pankratz 2018 assembled a German compound dataset of N=9415 compounds built from 48 first constituent (N1s), up to ten N1 for each of the seven pluralic linkers -_n_-, -_en_-, -_e_-, -_"e_-, -_"_-, -_er_-, -_"er_-. All N1s are countable nouns which are productively used in compounds both with and without the pluralic linking element. For each N1, up to 100 compound **tokens** with a non-pluralic (mostly zero or -_s_-) and up to 100 compound **tokens** with the pluralic linker were retrieved from DECOW16A. Since tokens and not types were counted, there is a number of duplicated constituent combinations (CC) in the data, though sometimes with alternating linkers. Besides, the original wordforms were preserved, and so compounds both in their Sg and Pl form appear, sometimes within the duplicated CC. Thus for example, the CC 'Apfel' + 'Baum' features occurrences 'Apfelbaum', 'Apfelbäume', 'Äpfelbaum', and 'Äpfelbäume' in the data. Note that no frequency threshold on the compounds was set while sampling the data.

What Schäfer & Pankratz 2018 were interested in regarding the ExtPE was whether the formal Pl form of a compound increases the probability of the pluralic linker element to occur. Going back to the example above, the question was: if the Sg form of 'Apfel' + 'Baum' is 'Apfelbaum', will the Pl form statistically tend to prefer 'Äpfelbäume' over 'Apfelbäume'?

To investigate this effect, Schäfer & Pankratz 2018 utilized the following methodology.

1. First, they created a 2x2 contingency table over the data with the following axes: non-pluralic vs. pluralic linker, and Sg vs. Pl compound form. The resulting table is below:

	|  | Sg | Pl |
	|---|---|---|
	| non-pluralic linker | 1574 | 3133 |
	| pluralic linker | 1474 | 3234 |

2. Second, they applied the Chi2 test to identify whether there is a relation between the two variables (the "plurality" of the linker vs. the formal number of the compound). The test produced a significant result at sig = 0.05 $(χ2 = 4.786, df = 1, p = 0.029)$.

3. Then, they measured the effect size with Cramer's V and revealed that it is quite low at $v = 0.023$.

4. Finally, the inspection of the symmetrical (standardised) residuals revealed that the diverging data points followed the wrong direction, that is, there were more non-pluralic linkers in Pl compounds that expected by chance ($-2.210$).

Schäfer & Pankratz 2018 conclude: even though the p-value is (still) significant, the Cramer’s V and the residual values reveal that even if there is some weak association, it is opposite from expected: compounds more often have non-pluralic linkers in the Sg form.

As a confirmation, the preceding Pankratz 2017 thesis was based on the same methodology and gave similar results for the ExtPE on a different dataset. Pankratz found only four individual N1s that undergo the ExtPE in the desired direction, and four that went in the opposite direction. The ExtPE hypothesis was still refuted because no effect was detected for the entire dataset.


## Objective

When scrutinizing the dataset from Schäfer & Pankratz 2018, a few groups of compounds could be detected that could erode the overall effect over the entire dataset:
* Compounds that only appear in one number. Under no observed number variation, we cannot make judgments about the behavior of these compounds in the opposite number.
* Compounds that (potentially) undergo the internal plural effect (IntPE). Since the IntPE works on a lexical level, it should be present in both numbers, so that both in Sg and Pl forms the pluralic linker is preferred (examples from the dataset: 'Äpfelkiste' vs. 'Äpfelkisten', 'Liederabend' vs. 'Liederabende'). Thus, the IntPE may interfere with the external plural effect and make the latter undetectable.
* Compounds whose N1s may take on the pluralic linker due to other constraints (examples from the dataset: 'Katzenfell' vs. 'Katzenfelle' because of schwa, 'Kinderbuch' vs. 'Kinderbücher' as person designation). Again, if the given N1 mostly takes a pluralic linker in its Sg form, it will most likely do so in Pl, making the ExtPE undetectable.

Our first hypothesis was the following: _after removing these "problematic" groups from the data, the ExtPE should be observable in the remaining compounds_. Correspondingly, _gradually letting the problematic groups back in should weaken the effect up to its vanishing_.


On the other hand, the ExtPE may not be present the standard German, since variation of type 'Apfelbaum' -- 'Äpfelbäume' is ungrammatical in standard German. If the ExtPE exists, it should be an immediate product of colloquial language, maybe even unintentional. This is indirectly supported by the fact that the compounds in the data did not undergo any frequency filtering. Therefore, we proposed the second hypothesis: _most (if not all) manifestations of the ExtPE will vanish after frequency filtering_. _A more severe filtering will lead to a more pronounced absence of the effect_.


## Data

<small>
Convention: <em>(N=x)</em> refers to the number of compound <b>tokens</b> in the dataset, <em>(UniqN=x)</em> refers to the number of unique compound <b>lemmata</b> in the dataset, <em>(UniqCN=x)</em> refers to the number of unique constituent combinations in the dataset (regardless of the linker), <em>(UniqN1N=x)</em> refers to the number of unique N1 <b>lemmata</b> in the dataset, "compounds" refers to "compound tokens" unless specified otherwise.
</small>

We prepared three modifications of the original Schäfer & Pankratz 2018 dataset resulting after removing the problematic groups gradually.
* `ic_alt` (**I**dentical **C**onstituent combinations, **ALT**ernating): compounds built from non-unique constituent combinations (regardless of the linker) appearing both in the Sg and the Pl forms | $(N=2318, UniqN=1246, UniqCN=869)$.
* `ic_alt_nipe` (**I**dentical **C**onstituent combinations, **ALT**ernating, **N**o **I**nt**PE**): compounds built from non-unique constituent combinations (regardless of the linker) appearing both in the Sg and the Pl forms and not undergoing the IntPE | $(N=1931, UniqN=1043, UniqCN=724)$.
* `ic_alt_nipe_npll` (**I**dentical **C**onstituent combinations, **ALT**ernating, **N**o **I**nt**PE**, **N**o **PL**uralic **L**inker allowed): compounds built from non-unique constituent combinations (regardless of the linker) appearing both in the Sg and the Pl forms and not undergoing the IntPE whose N1 may not attach a pluralic linker | $(N=1236, UniqN=665, UniqCN=468, UniqN1N=30)$.

In parallel, we defined three levels of frequency (the word counts (WCs) were obtained from DeReKo following the procedure outlined in Shmalts 2026, accessed mid June 2026):
* `lfreq` (low frequency): word count (WC) $> 0$, as in the original data.
* `mfreq` (moderate frequency): WC $>= 20$.
* `hfreq` (high frequency): WC $>= 100$.

During the studies, each of the three datasets was dynamically filtered to conform to the three frequency levels. Thus, nine unique data samples appear in the studies.


## Workflow

To evaluate the proposed hypothesis, we run four studies.

* Study 1 replicates the original ExtPE study from Schäfer & Pankratz 2018 on the nine possible data samples (three datasets x three frequency levels). It answers the general question whether the ExtPE is present (in any of the samples). Comparing the individual results from the samples will additionally give an overall idea of the impact of the problematic groups and the frequency level on ExtPE's presence and strengths.
* Study 2 expands study 1 and investigates the ExtPE for each individual N1 in each of the nine data samples, following Pankratz 2017. It aims at answering whether certain N1s are more sensitive to the ExtPE than the others.
* Study 3 focuses on the distribution of non-pluralic and pluralic linker in compounds in the Pl form only. It contrasts the distribution in the "cleanest" `ic_alt_nipe_npll` vs the two other datasets with an increasing share of the problematic groups. It provides a more detailed account of the effect of the problematic groups on ExtPE's presence and strengths.
* Study 4 contrasts the distribution of non-pluralic and pluralic linker in Pl compounds in the low frequency setting vs the moderate/high frequency setting, within each of the three dataset. It provides a more detailed account of the effect of the frequency level on ExtPE's presence and strengths.


## Summary of Results

### Study 1

* The ExtPE does not reach a statistical significance in any of the nine data samples. The p-values and the Cramer's V values are comparable across the three datasets along all three frequency settings.
* However, the p-values increase, while the Cramer's V values decrease consistently within each dataset, as the frequency level of the dataset is increased. This points out that ExtPE is much weaker in moderate/high frequency settings, which indirectly points towards the expected frequency effect on the ExtPE.

### Study 2

* N1s 'Apfel' and 'Bucht' undergo the ExtPE in the desired direction at marginal significance level sig = 0.1 (increased p-value threshold to account for the small sample sizes), but only in `ic_alt_nipe_npll` and `ic_alt_nipe` and only in the low frequency setting ('Apfel': $(χ2 = 3.242, df = 1, p = 0.072)$, $v = 0.265$; 'Bucht': $(χ2 = 2.716, df = 1, p = 0.099)$, $v = 0.243$). N1 'Person' undergoes the ExtPE in the desired direction at significance level close to sig = 0.05 in all three datasets, but, again, only in the low frequency setting ($(χ2 = 3.967, df = 1, p = 0.046)$, $v = 0.245$).
* The fact that the marginal significance disappears with 'Apfel' and 'Bucht' in the most "contaminated" dataset `ic_alt` indirectly points towards the effect of the problematic groups on the ExtPE.
* The fact that the (marginal) significance disappears with all three N1s in the moderate/high frequency settings indirectly points towards the effect of frequency on the ExtPE.
* The significant results of N1s 'Apfel' and 'Person' confirm finding of Pankratz 2017.
* However, none of the other six "significant" N1s reported by Pankratz 2017 reach statistical significance in any of the nine data samples.

### Study 3

* Comparison of the linker distributions in the Pl compounds in `ic_alt_nipe_npll` vs `ic_alt_nipe` does not produce statistical significance.
* However, comparing the "cleanest" `ic_alt_nipe_npll` and the most "contaminated" `ic_alt` reveals a statistically significant effect at sig = 0.05 ($(χ2 = 7.635, df = 1, p = 0.006)$, $v = 0.066$). The examination of the symmetrical (standardised) residuals revealed that the diverging data points followed the expected direction, that is, Pl compounds inserted more pluralic linkers in `ic_alt` and less in `ic_alt_nipe_npll` than expected by chance ($2.814$). Consequently, this means that `ic_alt` has more sources for a pluralic linker to appear, thus supporting the indirect evidence for the problematic group effect from Study 2, and partly confirming the effect.

### Study 4

* Comparison of the linker distributions in the Pl compounds of difference frequency levels produced statistical significance only in the `ic_alt_nipe_npll` dataset: low vs. moderate frequency reaches significance at sig = 0.05, and low vs. high frequency at sig = 0.005 (low vs. moderate: $(χ2 = 4.376, df = 1, p = 0.036)$, $v = 0.066$; low vs. high: $(χ2 = 7.755, df = 1, p = 0.005)$, $v = 0.09$). The examination of the symmetrical (standardised) residuals revealed that the diverging data points followed the expected direction, that is, Pl compounds inserted less pluralic linkers in moderate/high and more in low frequency setting than expected by chance ($-2.158$ and $-2.854$, respectively). This finding supports the indirect evidence for the frequency effect from Studies 1 and 2, and confirms the effect.
* The fact that more "contaminated" datasets did not exhibit a significant difference speaks in favor of the problematic group hypothesis and may be explained by that the additional sources of pluralic linker there erode the effect. This is attested by the fact that, while insignificant, the p-values still decrease, and the Cramer's V values increase there consistently with increasing the frequency level. Both evidence further indirectly support both the problematic group and the frequency effects.

The obtained results refute our first hypothesis that the ExtPE generally exists in less "contaminated" data. Conversely, they confirm our second hypothesis that any manifestations of the ExtPE are a product of the low frequency setting.

<small>
Note that the Cramer's V value did not cross the value of $0.1$ in any of the tests. That means that, even if an effect is statistically significant, the effect size is very small.
</small>

## Conclusion

While the theoritized ExtPE is not strong or consistent enough to be acknowledged as an established phenomenon in German, there exist arbitrary and scattered weak manifestations thereof. These manifestations occur more frequently in the low frequency setting that in the moderate/high frequency setting, with a statistically significant difference. They are found prevalently in compounds that would otherwise not insert a pluralic linkers, with a statistically significant difference as compared to compounds that may do so. We conclude: while inconsistently and pronounced weakly, certain sparks of the ExtPE may occur in immediate colloquial language. If it happens, the object of the ExtPE is a compounds that would otherwise not insert a pluralic linker. In compounds that may do so, the ExtPE is masked and not detectable.

In [1]:
import os
import pandas as pd
from scipy.stats import chi2_contingency
from statsmodels.stats.contingency_tables import Table
import math
from tqdm import tqdm
from collections import defaultdict
from itertools import product
from typing import Tuple, Optional

In [2]:
sp18_ext_path = "../resources/developed/sp18/external_effect"

res_outdir = "../out/external_effect"

incsv_args = {
	"sep":"\t",
    "header":0,
    "index_col":"const_comb",
    # all str, WC int, is linker pluralic bool
    "dtype": defaultdict(
        lambda: str,
        wc="int",
        is_linker_pl="bool"
    ),
	# = csv.QUOTE_NONE, separate by tabs only
    "quoting": 3
}

outcsv_args = {
    "sep": "\t",
    "index": True,
    "header": True
}

In [3]:
def calc_pll_shares(
    sp18_sample: pd.DataFrame
) -> Tuple[pd.DataFrame, pd.DataFrame]:

    # calculate absolute counts and shares of compounds 
    # with pluralic linkers in Sg vs. Pl forms

    sp18_sample_pll_counts_data = {}
    for const_comb, group in sp18_sample.groupby("const_comb"):
        for num in ["sg", "pl"]:
            sp18_sample_pll_counts_data[(const_comb, f"num_{num}")] = {
                "l_sg": len(
                    group[(group["n2_num"] == num) &
                    (~group["is_linker_pl"])]
                ),
                "l_pl": len(
                    group[(group["n2_num"] == num) &
                    (group["is_linker_pl"])]
                )
            }

    sp18_sample_pllcounts = pd.DataFrame(sp18_sample_pll_counts_data).T
    sp18_sample_pllcounts["pl_share"] = sp18_sample_pllcounts["l_pl"] / (
        sp18_sample_pllcounts["l_sg"] + sp18_sample_pllcounts["l_pl"]
    )

    sp18_sample_pllshares = sp18_sample_pllcounts \
        .unstack()["pl_share"]  \
        [["num_sg", "num_pl"]]

    return sp18_sample_pllcounts, sp18_sample_pllshares

In [ ]:
def sp18_orig_analysis(
    contingency_table: pd.DataFrame,
    label_1: str,
    label_2: str
) -> pd.DataFrame:

    # Methodology from the original [schaefer_pankratz_2018:26] paper:
    # 0. Create contingency table:
    # n2_num (Sg vs. Pl) x n1_pl_marker (non- vs. pluralic linker).
    # 1. Perform the chi-squared test of independence over the table
    # to assess the statistical significance of the association between
    # the Pl form of N2 and the presence of a pluralic linker in N1.
    # 2. Perform the Cramer's V test to assess the strength
    # of the association.
    # 3. Inspect symmetrical standardized residuals to identify
    # the cells that contribute to the association, and in which direction.

    # 1. Perform the chi-squared test.

    # even though I didn't find the original R code
    # of [schaefer_pankratz_2018] for this experiment,
    # the `chi2_contingency` function from `scipy.stats`
    # produced the same results as in the paper
    # on the same contingency table, so we can be
    # confident that we are replicating the same analysis
    chi2_res = chi2_contingency(contingency_table)

    # 2. Perform the Cramer's V test to assess 
    # the strength of the association.

    # the original R code for Cramer's V is available in
    # linkingelements/Data/R/functions.R, and is as follows:
    # 
    #   cramer.v <- function(chisq) {
    #       unname(sqrt(chisq$statistic/(sum(chisq$observed)*min(dim(chisq$observed)-1))))
    #   }
    #
    # we will reconstruct it in Python:
    #   dim(chisq$observed) -> ic_alt_nipe_sg_l_ct.shape
    #
    #   min(dim(chisq$observed)-1) -> min(
    #       ic_alt_nipe_sg_l_ct.shape[0] - 1,
    #       ic_alt_nipe_sg_l_ct.shape[1] - 1
    #   )
    # 
    #   sum(chisq$observed) -> ic_alt_nipe_sg_l_ct.values.sum()
    #
    #   unname -> [irrelevant for Python]
    cramer_v_val = math.sqrt(
        chi2_res.statistic / (
            contingency_table.values.sum() *
            min(
                contingency_table.shape[0] - 1,
                contingency_table.shape[1] - 1
            )
        )
    )

    # DEPRECATED: for 2x2 contingency tables, Cohen's W
    # is effectively identical to Cramer's V
    # # the original R code for Cohen's W is available in
    # # linkingelements/Data/R/functions.R, and is as follows:
    # # 
    # #   # cohen.w <- function(chisq) {
    # #       cramer.v(chisq) * sqrt(min(dim(chisq$observed)-1))
    # #   }
    # cohen_w_val = cramer_v_val * math.sqrt(
    #     min(
    #         contingency_table.shape[0] - 1,
    #         contingency_table.shape[1] - 1
    #     )
    # )

    # 3. Inspect symmetrical standardized residuals to identify
    # the cells that contribute to the association, and in which direction.

    # even though I didn't find the original R code
    # of [schaefer_pankratz_2018] for this experiment,
    # the `standardized_resids` property of
    # `statsmodels.stats.contingency_tables.Table`
    # produced the same results as in the paper
    # on the same contingency table, so we can be
    # confident that we are replicating the same analysis
    resids = Table(contingency_table)    \
        .standardized_resids.round(3)
    
    chi2df = pd.Series(
        data={
            "N": contingency_table.values.sum(),
            "df": chi2_res.dof,
            "chi2": chi2_res.statistic.round(3),
            "p": chi2_res.pvalue,
            "cramer_v": round(cramer_v_val, 3),
            # "cohen_w": round(cohen_w_val, 3),
            "resids_cong": resids.loc["l_pl", label_1].item(),
            "resids_incong": resids.loc["l_pl", label_2].item()
        }
    ).round(3)
    chi2df["N"] = chi2df["N"].astype(int)
    chi2df["df"] = chi2df["df"].astype(int)

    return chi2df

In [5]:
keys = [
        # Compounds built from non-unique constituent combinations (regardless 
        # of the linker) appearing both in the Sg and the Pl forms
        # and not undergoing the IntPE whose N1 may not attach a pluralic linker
        # (N=1236, UniqN=665, UniqCN=468, UniqN1N=30)
        "ic_alt_nipe_npll",

        # Compounds built from non-unique constituent combinations (regardless 
        # of the linker) appearing both in the Sg and the Pl forms
        # and not undergoing the IntPE
        # (N=1931, UniqN=1043, UniqCN=724)
        "ic_alt_nipe",

        # Compounds built from non-unique constituent combinations (regardless 
        # of the linker) appearing both in the Sg and the Pl forms
        # (N=2318, UniqN=1246, UniqCN=869)
        "ic_alt"
    ]

freq_levels = [
    ("lfreq", 0), # all frequencies, >= 0
    ("mfreq", 20),  # moderate frequency, >= 20
    ("hfreq", 100)  # high frequency, >= 100
]

# Study 1

Compound groups

In [ ]:
def run_study_1(
	sp18_sample: pd.DataFrame,
	outdir: Optional[str]=None
) -> Tuple[
	pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.Series
]:

	# calculate absolute counts and shares of compounds 
	# with pluralic linkers in Sg vs. Pl forms
	(
		sp18_sample_pllcounts,
		sp18_sample_pllshares
	) = calc_pll_shares(sp18_sample)

	# shares desc
	sp18_sample_pllshares_desc = sp18_sample_pllshares.describe()

	# create contingency table replicating [schaefer_pankratz_2018:26]
	# n2_num (Sg vs. Pl) x n1_pl_marker (non- vs. pluralic linker).
	contingency_table = sp18_sample_pllcounts \
		.groupby(level=1)[["l_sg", "l_pl"]].sum()   \
		.T  \
		# [["num_sg", "num_pl"]]
	# perform the original analysis from [schaefer_pankratz_2018:26]
	chi2df = sp18_orig_analysis(
		contingency_table,
		label_1="num_pl",
		label_2="num_sg"
	)

	if outdir:

		os.makedirs(outdir, exist_ok=True)

		sp18_sample_pllcounts.to_csv(
			os.path.join(outdir, "pllcounts.tsv"),
			**outcsv_args
		)
		sp18_sample_pllshares.to_csv(
			os.path.join(outdir, "pllshares.tsv"),
			**outcsv_args
		)

		sp18_sample_pllshares_desc.to_csv(
			os.path.join(outdir, "pllshares_desc.tsv"),
			**outcsv_args
		)

		contingency_table.to_csv(
			os.path.join(outdir, "contingency_table.tsv"),
			**outcsv_args
		)
		chi2df.to_csv(
			os.path.join(outdir, "chi2.tsv"),
			**{**outcsv_args, "header": False}
		)

	return (
		sp18_sample_pllcounts, sp18_sample_pllshares, 
		sp18_sample_pllshares_desc,
		contingency_table, chi2df
	)

In [ ]:
chi2_summaries = []
with tqdm(
    total=len(keys) * len(freq_levels), 
    desc="SP18 compound group ExtPE study"
) as pbar:

    for sample_sfx in keys:

        sp18_sample = pd.read_csv(
            os.path.join(sp18_ext_path, f"{sample_sfx}.tsv"),
            **incsv_args
        )

        chi2dfs = []
        outdir = os.path.join(res_outdir, sample_sfx)

        # three levels of frequency
        for freq_sfx, freq_threshold in freq_levels:

            sp18_subsample = sp18_sample[sp18_sample["wc"] >= freq_threshold]
            *_, chi2df = run_study_1(sp18_subsample, os.path.join(outdir, freq_sfx))
            chi2df.name = freq_sfx
            chi2dfs.append(chi2df)
            
            pbar.update(1)

        chi2_summary = pd.concat(chi2dfs, axis=1)
        chi2_summary.to_csv(
            os.path.join(outdir, "chi2_summary.tsv"),
            **outcsv_args
        )
        chi2_summaries.append(chi2_summary)

SP18 compound group ExtPE study: 100%|██████████| 9/9 [00:03<00:00,  2.62it/s]

In [8]:
chi2_summary = pd.concat(chi2_summaries, keys=keys)  \
    .swaplevel(0, 1)    \
    .sort_index(level=0, sort_remaining=False)  \
    .reindex(chi2df.index, level=0)
chi2_summary.to_csv(
    os.path.join(res_outdir, "chi2_summary.tsv"),
    **outcsv_args
)
chi2_summary

                                   lfreq     mfreq     hfreq
N             ic_alt_nipe_npll  1235.000   808.000   694.000
              ic_alt_nipe       1930.000  1248.000  1076.000
              ic_alt            2317.000  1516.000  1308.000
df            ic_alt_nipe_npll     1.000     1.000     1.000
              ic_alt_nipe          1.000     1.000     1.000
              ic_alt               1.000     1.000     1.000
chi2          ic_alt_nipe_npll     1.785     0.049     0.026
              ic_alt_nipe          2.051     0.139     0.000
              ic_alt               1.884     0.175     0.012
p             ic_alt_nipe_npll     0.181     0.824     0.872
              ic_alt_nipe          0.152     0.710     1.000
              ic_alt               0.170     0.676     0.914
cramer_v      ic_alt_nipe_npll     0.038     0.008     0.006
              ic_alt_nipe          0.033     0.011     0.000
              ic_alt               0.029     0.011     0.003
resids_cong   ic_alt_nipe_npll     1.394     0.296    -0.242
              ic_alt_nipe          1.478     0.430     0.028
              ic_alt               1.414     0.470     0.163
resids_incong ic_alt_nipe_npll    -1.394    -0.296     0.242
              ic_alt_nipe         -1.478    -0.430    -0.028
              ic_alt              -1.414    -0.470    -0.163

In [ ]:
there are differnt N1s with different CCs
...

In [ ]:
Neither Wilcoxon, nor paired t-test can be used because ...

# Study 2

Individual N1s.

In [9]:
n1s = sp18_sample["n1"].unique()
n1s

<StringArray>
[      'apfel',         'bad',        'ball',        'bett',        'bild',
       'brett',       'brief',        'buch',       'bucht',       'dämon',
          'ei', 'eigenschaft',     'element',        'frau',       'gerät',
    'geräusch',    'geschenk',     'gitarre',        'hand',        'haus',
        'hemd',        'hund',       'katze',        'kind',     'kommune',
        'lied',        'loch',      'mutter',       'nagel',      'nation',
         'ohr',      'person',     'produkt',   'projektor',         'rad',
     'schloss',     'schwert',   'schwester',       'sonne',       'stadt',
       'vater',       'vogel',         'weg',        'wurm',        'zahn',
       'zitat']
Length: 46, dtype: str

In [10]:
chi2_summaries = defaultdict(dict)
sign_n1s = []
with tqdm(
    total=len(keys) * len(freq_levels) * len(n1s), 
    desc="SP18 N1 ExtPE study"
) as pbar:

    for sample_sfx, n1 in product(keys, n1s):

        sp18_sample = pd.read_csv(
            os.path.join(sp18_ext_path, f"{sample_sfx}.tsv"),
            **incsv_args
        )

        chi2dfs = []
        is_sign = False

        # three levels of frequency
        for freq_sfx, freq_threshold in freq_levels:

            sp18_subsample = sp18_sample[
                (sp18_sample["wc"] >= freq_threshold) &
                (sp18_sample["n1"] == n1)
            ]

            try:
                *_, chi2df = run_study_1(sp18_subsample)
                chi2df.name = freq_sfx
                chi2dfs.append(chi2df)
                # increased p-value to account for small sample sizes;
                # the final decision will be based on Cramer's V and resids
                if chi2df["p"] < 0.1:
                    sign_n1s.append(n1)
            except KeyError, ValueError:
                # all_nipe_npll is missing a few N1s;
                # otherwise, after freq filtering
                # not all CCs have valid contingency tables
                pass

            pbar.update(1)
            
        chi2_summary = pd.concat(chi2dfs, axis=1) if chi2dfs else None
        chi2_summaries[n1][sample_sfx] = chi2_summary

SP18 N1 ExtPE study: 100%|██████████| 414/414 [00:05<00:00, 71.86it/s]

In [11]:
for n1, chi2_sum in chi2_summaries.items():

    chi2_summary = pd.concat(chi2_sum.values(), keys=chi2_sum.keys())  \
        .swaplevel(0, 1)    \
        .sort_index(level=0, sort_remaining=False)  \
        .reindex(chi2df.index, level=0)
    chi2_summary.to_csv(
        os.path.join(res_outdir, "n1", "all", f"{n1}.tsv"),
        **outcsv_args
    )

In [26]:
# TODO: optimize
# rerun significant N1s and save the outputs
chi2_summaries = defaultdict(dict)
with tqdm(
    total=len(keys) * len(freq_levels) * len(sign_n1s), 
    desc="SP18 significant N1 ExtPE study"
) as pbar:
    
    for sample_sfx, n1 in product(keys, sign_n1s):

        sp18_sample = pd.read_csv(
            os.path.join(sp18_ext_path, f"{sample_sfx}.tsv"),
            **incsv_args
        )

        chi2dfs = []
        outdir = os.path.join(res_outdir, "n1", n1, sample_sfx)
        is_sign = False

        # three levels of frequency
        for freq_sfx, freq_threshold in freq_levels:

            sp18_subsample = sp18_sample[
                (sp18_sample["wc"] >= freq_threshold) &
                (sp18_sample["n1"] == n1)
            ]

            try:
                *_, chi2df = run_study_1(
                    sp18_subsample,
                    os.path.join(outdir, freq_sfx)
                )
                chi2df.name = freq_sfx
                chi2dfs.append(chi2df)
            except KeyError, ValueError:
                # all_nipe_npll is missing a few N1s;
                # otherwise, after freq filtering
                # not all CCs have valid contingency tables
                pass

            pbar.update(1)
            
        chi2_summary = pd.concat(chi2dfs, axis=1) if chi2dfs else None
        if chi2_summary is not None:
            chi2_summary.to_csv(
                os.path.join(outdir, "chi2_summary.tsv"),
                **outcsv_args
            )
            chi2_summaries[n1][sample_sfx] = chi2_summary

SP18 significant N1 ExtPE study: 100%|██████████| 63/63 [00:01<00:00, 62.92it/s]

In [27]:
for n1, chi2_sum in chi2_summaries.items():

    chi2_summary = pd.concat(chi2_sum.values(), keys=chi2_sum.keys())  \
        .swaplevel(0, 1)    \
        .sort_index(level=0, sort_remaining=False)  \
        .reindex(chi2df.index, level=0)
    chi2_summary.to_csv(
        os.path.join(res_outdir, "n1", n1, "chi2_summary.tsv"),
        **outcsv_args
    )

In [14]:
apfel = pd.concat(chi2_summaries["apfel"])  \
    .swaplevel(0, 1)    \
    .sort_index(level=0, sort_remaining=False)  \
    .reindex(chi2df.index, level=0)

In [15]:
apfel.loc[["p", "cramer_v"]]

                           lfreq  mfreq  hfreq
p        ic_alt_nipe_npll  0.072  0.712  0.276
         ic_alt_nipe       0.072  0.712  0.276
         ic_alt            0.135  0.712  0.276
cramer_v ic_alt_nipe_npll  0.265  0.064  0.214
         ic_alt_nipe       0.265  0.064  0.214
         ic_alt            0.207  0.064  0.214

In [16]:
person = pd.concat(chi2_summaries["person"])  \
    .swaplevel(0, 1)    \
    .sort_index(level=0, sort_remaining=False)  \
    .reindex(chi2df.index, level=0)

In [17]:
person.loc[["p", "cramer_v"]]

                           lfreq
p        ic_alt_nipe_npll  0.052
         ic_alt_nipe       0.052
         ic_alt            0.046
cramer_v ic_alt_nipe_npll  0.272
         ic_alt_nipe       0.272
         ic_alt            0.245

# Study 3

Frequency effects.

In [ ]:
def run_study_3(
	sp18_sample_1: pd.DataFrame,
	sp18_sample_2: pd.DataFrame,
	label_1: str,
	label_2: str,
	outdir: Optional[str]=None
) -> Tuple[
	pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.Series
]:

	# calculate absolute counts of compounds 
	# with pluralic linkers in Pl forms
	# in the two settings
	pllcounts_1, pllshares_1 = calc_pll_shares(sp18_sample_1)
	pllcounts_2, pllshares_2 = calc_pll_shares(sp18_sample_2)
	# extract only values in Pl form
	pllcounts_1 = pllcounts_1.swaplevel(0, 1).loc["num_pl"]
	pllcounts_2 = pllcounts_2.swaplevel(0, 1).loc["num_pl"]
	# since we have different portions of data,
	# some constituent combinations will be
	# non-existent in one of the samples; force
	# mask them with NaN before joining
	all_ccs = pllcounts_1.index.union(pllcounts_2.index)
	pllcounts_1 = pllcounts_1.reindex(all_ccs)
	pllcounts_2 = pllcounts_2.reindex(all_ccs)
	sp18_samples_pllcounts = pd.concat(
		(pllcounts_1, pllcounts_2),
		keys=[label_1, label_2]
	).swaplevel(0, 1)	\
	.sort_index(level=0, sort_remaining=False)
		
	# shares desc
	pllshares_1 = pllshares_1["num_pl"]
	pllshares_1.name = label_1
	pllshares_2 = pllshares_2["num_pl"]
	pllshares_2.name = label_2
	sp18_samples_pllshares = pd.concat((pllshares_1, pllshares_2), axis=1)
	sp18_samples_pllshares_desc = sp18_samples_pllshares.describe()

	contingency_table = sp18_samples_pllcounts \
		.groupby(level=1).sum()   \
		.T

	chi2df = sp18_orig_analysis(
		contingency_table,
		label_1=label_1,
		label_2=label_2
	)

	if outdir:

		os.makedirs(outdir, exist_ok=True)

		sp18_samples_pllcounts.to_csv(
			os.path.join(outdir, "pllcounts.tsv"),
			**outcsv_args
		)
		sp18_samples_pllshares.to_csv(
			os.path.join(outdir, "pllshares.tsv"),
			**outcsv_args
		)

		sp18_samples_pllshares_desc.to_csv(
			os.path.join(outdir, "pllshares_desc.tsv"),
			**outcsv_args
		)

		contingency_table.to_csv(
			os.path.join(outdir, "contingency_table.tsv"),
			**outcsv_args
		)
		chi2df.to_csv(
			os.path.join(outdir, "chi2.tsv"),
			**{**outcsv_args, "header": False}
		)

	return (
		sp18_samples_pllcounts, sp18_samples_pllshares, 
		sp18_samples_pllshares_desc,
		contingency_table, chi2df
	)

In [32]:
# problematic groups
sp18_sample_2 = pd.read_csv(
    os.path.join(sp18_ext_path, f"{keys[0]}.tsv"),
    **incsv_args
)
with tqdm(total=len(keys) - 1, desc="SP18 data quality ExtPE study") as pbar:

    chi2dfs = []

    for sample_sfx in keys[1:]:

        sp18_sample_1 = pd.read_csv(
            os.path.join(sp18_ext_path, f"{sample_sfx}.tsv"),
            **incsv_args
        )

        outdir = os.path.join(res_outdir, "paired", "data_quality")

        # we expect more pluralic linkers in the first sample
        *_, chi2df = run_study_3(
            sp18_sample_1,
            sp18_sample_2,
            label_1=sample_sfx,
            label_2=keys[0],
            outdir=os.path.join(outdir, f"{keys[0]}_vs_{sample_sfx}")
        )
        chi2df.name = f"{keys[0]}_vs_{sample_sfx}"
        chi2dfs.append(chi2df)
        
        pbar.update(1)

    chi2_summary = pd.concat(chi2dfs, axis=1)
    chi2_summary.to_csv(
        os.path.join(outdir, "chi2_summary.tsv"),
        **outcsv_args
    )
    chi2_summaries.append(chi2_summary)

SP18 data quality ExtPE study: 100%|██████████| 2/2 [00:01<00:00,  1.02it/s]

In [33]:
chi2_summary

               ic_alt_nipe_npll_vs_ic_alt_nipe  ic_alt_nipe_npll_vs_ic_alt
N                                     1560.000                    1735.000
df                                       1.000                       1.000
chi2                                     0.275                       7.635
p                                        0.600                       0.006
cramer_v                                 0.013                       0.066
resids_cong                              0.577                       2.814
resids_incong                           -0.577                      -2.814

In [34]:
# frequency groups
with tqdm(
    total=len(keys) * (len(freq_levels) - 1),
    desc="SP18 data quality ExtPE study"
) as pbar:

    chi2_summaries = []

    for sample_sfx in keys:

        sp18_sample_2 = pd.read_csv(
            os.path.join(sp18_ext_path, f"{sample_sfx}.tsv"),
            **incsv_args
        )

        chi2dfs = []
        outdir = os.path.join(res_outdir, "paired", "freq", sample_sfx)

        # three levels of frequency
        for freq_sfx, freq_threshold in freq_levels[1:]:

            sp18_sample_1 = sp18_sample_2[(sp18_sample_2["wc"] >= freq_threshold)]

            try:
                # we expect more pluralic linkers in the first sample
                *_, chi2df = run_study_3(
                    sp18_sample_1,
                    sp18_sample_2,
                    label_1=freq_sfx,
                    label_2="lfreq",
                    outdir=os.path.join(outdir, f"lfreq_vs_{freq_sfx}")
                )
                chi2df.name = f"lfreq_vs_{freq_sfx}"
                chi2dfs.append(chi2df)
            except KeyError, ValueError:
                # all_nipe_npll is missing a few N1s;
                # otherwise, after freq filtering
                # not all CCs have valid contingency tables
                pass

            pbar.update(1)

        chi2_summary = pd.concat(chi2dfs, axis=1) if chi2dfs else None
        if chi2_summary is not None:
            chi2_summary.to_csv(
                os.path.join(outdir, "chi2_summary.tsv"),
                **outcsv_args
            )
            chi2_summaries.append(chi2_summary)

SP18 data quality ExtPE study: 100%|██████████| 6/6 [00:05<00:00,  1.19it/s]

In [36]:
chi2_summary = pd.concat(chi2_summaries, keys=keys)  \
    .swaplevel(0, 1)    \
    .sort_index(level=0, sort_remaining=False)  \
    .reindex(chi2df.index, level=0)
chi2_summary.to_csv(
    os.path.join(res_outdir, "paired", "freq", "chi2_summary.tsv"),
    **outcsv_args
)
chi2_summary

                                lfreq_vs_mfreq  lfreq_vs_hfreq
N             ic_alt_nipe_npll        1010.000         953.000
              ic_alt_nipe             1580.000        1494.000
              ic_alt                  1876.000        1772.000
df            ic_alt_nipe_npll           1.000           1.000
              ic_alt_nipe                1.000           1.000
              ic_alt                     1.000           1.000
chi2          ic_alt_nipe_npll           4.376           7.755
              ic_alt_nipe                1.718           2.933
              ic_alt                     0.939           1.952
p             ic_alt_nipe_npll           0.036           0.005
              ic_alt_nipe                0.190           0.087
              ic_alt                     0.332           0.162
cramer_v      ic_alt_nipe_npll           0.066           0.090
              ic_alt_nipe                0.033           0.044
              ic_alt                     0.022           0.033
resids_cong   ic_alt_nipe_npll          -2.158          -2.854
              ic_alt_nipe               -1.363          -1.767
              ic_alt                    -1.016          -1.446
resids_incong ic_alt_nipe_npll           2.158           2.854
              ic_alt_nipe                1.363           1.767
              ic_alt                     1.016           1.446