### Small script to compute the size of the datasets for constraint verfication.

In [1]:
# make the root directory the pwd
%cd ..

/Users/maksimshmalts/Documents/DieKonstraintsPrivat/semrel_comp_corp_study-private

In [2]:
from data_utils.load_datasets import load_gecodb, load_sp18
from data_utils.gecodb_compound_parser import Compound

In [3]:
get_linker_gecodb = lambda g: "_" if len((s := g.split("_"))) == 2 else s[1]

get_linker = lambda g: (
    "\"" if (l := Compound(g).linkers[0]).adds_umlaut else ""
) + l.morph

#### GeCoDB_v06

In [4]:
gecodb_v06_path = "resources/comp_constr_corp_study_mar26/gecodb_v06.tsv"
gecodb_v06 = load_gecodb(gecodb_v06_path)
gecodb_v06.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,n1_mass_freq,n2_lemma,n2_freq
comp_gecodb,,,,,,,,
atom_kern,Atomkern,4953,atom,29103,255,561102,kern,389265
abwicklung_+s_phase,Abwicklungsphase,72,abwicklung,70352,52,8072,phase,532977
markt_passage,Marktpassage,1114,markt,2649376,657,1463426,passage,164576
bild_landschaft,Bildlandschaft,95,bild,3732418,672,1596949,landschaft,503653
spieler_vorstellung,Spielervorstellung,111,spieler,2292236,222,235231,vorstellung,1131165
kraut_+=er_aroma,Kräuteraroma,172,kraut,156000,288,114928,aroma,64186
wirkung_+s_beziehung,Wirkungsbeziehung,34,wirkung,593084,70,80832,beziehung,829299
ausbildung_+s_schiff,Ausbildungsschiff,581,ausbildung,1159809,435,685397,schiff,689036
wohnung_+s_verbot,Wohnungsverbot,56,wohnung,1994713,275,491379,verbot,360234
kanzler_sturz,Kanzlersturz,529,kanzler,446252,91,209511,sturz,226255

In [5]:
gecodb_v06["linker_gecodb"] = gecodb_v06.index.map(get_linker_gecodb)
gecodb_v06["linker"] = gecodb_v06.index.map(get_linker)

In [6]:
len(gecodb_v06)

282767

In [7]:
len(gecodb_v06["n1_lemma"].unique())

3614

In [8]:
# for L2P
# note that, even though gecodb_v06 distinguishes between linker allomorphs,
# (e.g. _+n_ vs. _+en_), the number of N1+linker is the same on practive
# no matter whether we count N1+(linker morph) or N1+(linker allomorph);
# this is explained by the fact that the allomorphs are distributed
# complementarily, and there are no cases documented in which one N1 may attach
# two allomorphs of the same linker in different compounds
gecodb_v06["n1+linker"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker"]
gecodb_v06["n1+linker_gecodb"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker_gecodb"]
len(gecodb_v06["n1+linker"].unique()), len(gecodb_v06["n1+linker_gecodb"].unique())

(4870, 4870)

In [9]:
gecodb_v06["linker"].unique()

<ArrowStringArray>
['', 'es', '"er', 's', '"', 'e', 'en', '"e', 'ens']
Length: 9, dtype: str

In [10]:
gecodb_v06["linker_gecodb"].unique()

<ArrowStringArray>
['_', '+es', '+=er', '+s', '+=', '+e', '+n', '+=e', '+en', '+ens', '+ns']
Length: 11, dtype: str

#### GeCoDB_v07

In [11]:
gecodb_v07_path = "resources/developed/gecodb_v07.tsv"
gecodb_v07 = load_gecodb(gecodb_v07_path)
gecodb_v07.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,linker,is_pll,umlaut_applied,n2_lemma,n2_freq
comp_gecodb,,,,,,,,,,
unternehmen_+s_retter,Unternehmensretter,33,unternehmen,5400908,427,_+s_,False,False,retter,118802
gemüse_firma,Gemüsefirma,21,gemüse,273935,211,_,False,False,firma,2925009
foto_glück,Fotoglück,26,foto,5811265,340,_,False,False,glück,1405373
deck_haar,Deckhaar,1119,deck,51619,76,_,False,False,haar,609902
evakuierung_+s_mission,Evakuierungsmission,563,evakuierung,45114,42,_+s_,False,False,mission,238334
millimeter_entscheidung,Millimeterentscheidung,363,millimeter,115704,10,_,False,False,entscheidung,2835699
mann_+=er_wahn,Männerwahn,59,mann,8392866,477,_+=er_,True,True,wahn,31167
benutzung_+s_spur,Benutzungsspur,44,benutzung,44585,26,_+s_,False,False,spur,487330
freiheit_+s_forschung,Freiheitsforschung,63,freiheit,780583,153,_+s_,False,False,forschung,489614
konversion_+s_störung,Konversionsstörung,31,konversion,15571,39,_+s_,False,False,störung,185342

In [12]:
gecodb_v07["linker_gecodb"] = gecodb_v07["linker"].copy()
gecodb_v07["linker"] = gecodb_v07.index.map(get_linker)

In [13]:
len(gecodb_v07)

275409

In [14]:
len(gecodb_v07["n1_lemma"].unique())

3594

In [15]:
# for L2P;
gecodb_v07["n1+linker"] = gecodb_v07["n1_lemma"] + "_" + gecodb_v07["linker"]
gecodb_v07["n1+linker_gecodb"] = gecodb_v07["n1_lemma"] + "_" + gecodb_v07["linker_gecodb"]
len(gecodb_v07["n1+linker"].unique()), len(gecodb_v07["n1+linker_gecodb"].unique())

(4743, 4743)

In [16]:
gecodb_v07["linker"].unique()

<ArrowStringArray>
['', 'es', '"er', 's', 'er', '"', 'e', 'en', '"e', 'ens']
Length: 10, dtype: str

In [17]:
gecodb_v07["linker_gecodb"].unique()

<ArrowStringArray>
[     '_',  '_+es_', '_+=er_',   '_+s_',  '_+er_',   '_+=_',   '_+e_',
   '_+n_',  '_+=e_',  '_+en_', '_+ens_',  '_+ns_']
Length: 12, dtype: str

#### SP18_Pl_Constr

In [18]:
sp18_pl_constr_path = "resources/developed/sp18/sp18_pl_constr.tsv"
sp18_pl_constr = load_sp18(sp18_pl_constr_path)
sp18_pl_constr.sample(10)

,n1,n2,n1_pl_marker,n1_sem,is_linker_pl,wc
gecodb,,,,,,
frau_+en_schuh,frau,schuh,_+en_,ind,True,1690
schloss_turm,schloss,turm,_+=er_,ind,False,3188
stadt_+=e_atlas,stadt,atlas,_+=e_,konvc,True,215
produkt_empfehlung,produkt,empfehlung,_+e_,ind,False,511
frau_+en_bild,frau,bild,_+en_,ind,True,14592
haus_rind,haus,rind,_+=er_,ind,False,484
ball_vortrag,ball,vortrag,_+=e_,ind,False,439
frau_+en_hand,frau,hand,_+en_,ind,True,3708
katze_+n_falle,katze,falle,_+n_,ind,True,141
rad_wechsel,rad,wechsel,_+=er_,coll,False,1411

In [19]:
len(sp18_pl_constr)

2304

In [20]:
len(sp18_pl_constr["n1"].unique())

43

In [21]:
# for n1+sem (pluralic constraints)
len((sp18_pl_constr["n1"] + "+" + (sp18_pl_constr["n1_sem"] == "ind").astype(str)).unique())

77

In [22]:
# for L2P
# since sp18_pl_constr marks all linker allomorphs
# differently (e.g. _+n_ vs. _+en_), we first
# parse them into their morphs
sp18_pl_constr["linker"] = sp18_pl_constr.index.map(get_linker)
sp18_pl_constr["n1+linker"] = sp18_pl_constr["n1"] + "_" + sp18_pl_constr["linker"]
len(sp18_pl_constr["n1+linker"].unique())

86

In [23]:
sp18_pl_constr["linker"].unique()

<ArrowStringArray>
['"', '', '"er', '"e', 'en', 'er', 'e', 's']
Length: 8, dtype: str

In [24]:
# linker = lambda n1l: "_" if not "_" in n1l else n1l.split("_")[1]
sp18_pl_constr["linker_gecodb"] = sp18_pl_constr.index.map(get_linker_gecodb)
sp18_pl_constr["linker_gecodb"].unique()

<ArrowStringArray>
['+=', '_', '+=er', '+=e', '+en', '+er', '+e', '+s', '+n']
Length: 9, dtype: str