### Small script to compute the size of the datasets for constraint verfication.

In [1]:
# make the root directory the pwd
%cd ..

/Users/maxschmaltz/Documents/DieKonstraintsPrivat/semrel_comp_corp_study-private

In [2]:
import re

from data_utils.load_datasets import load_gecodb, load_sp18

#### GeCoDB_v06

In [3]:
gecodb_v06_path = "resources/comp_constr_corp_study_mar26/gecodb_v06.tsv"
gecodb_v06 = load_gecodb(gecodb_v06_path)
gecodb_v06.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,n1_mass_freq,n2_lemma,n2_freq
comp_gecodb,,,,,,,,
flüchtling_+s_streik,Flüchtlingsstreik,26,flüchtling,950891,174,401195,streik,285370
titan_brille,Titanbrille,24,titan,32325,28,2434,brille,162292
erholung_+s_insel,Erholungsinsel,171,erholung,203879,104,81361,insel,815449
film_schüler,Filmschüler,59,film,2531034,659,830598,schüler,3260549
wirtschaft_+s_kuchen,Wirtschaftskuchen,38,wirtschaft,1763302,683,2141662,kuchen,487855
wasser_stelle,Wasserstelle,6563,wasser,2264315,946,1678740,stelle,1639478
freiheit_+s_erklärung,Freiheitserklärung,31,freiheit,780583,153,232266,erklärung,623713
handel_+s_forschung,Handelsforschung,1641,handel,649201,441,848188,forschung,489614
auto_aufbruch,Autoaufbruch,5974,auto,3094561,574,1206404,aufbruch,125126
kurs_notiz,Kursnotiz,131,kurs,1402498,304,557153,notiz,90345

In [4]:
len(gecodb_v06)

282767

In [5]:
len(gecodb_v06["n1_lemma"].unique())

3613

In [6]:
# for L2P
n1_linker = lambda g: re.sub(r"_[^_]+$", "", g)
gecodb_v06["n1+linker"] = gecodb_v06.index.map(n1_linker)
len(gecodb_v06["n1+linker"].unique())

4870

In [7]:
linker = lambda n1l: "_" if not "_" in n1l else n1l.split("_")[1]
gecodb_v06["linker"] = gecodb_v06["n1+linker"].map(linker)
gecodb_v06["linker"].unique()

<StringArray>
['_', '+es', '+=er', '+s', '+=', '+e', '+n', '+=e', '+en', '+ens', '+ns']
Length: 11, dtype: str

#### GeCoDB_v07

In [8]:
gecodb_v07_path = "resources/developed/gecodb_v07.tsv"
gecodb_v07 = load_gecodb(gecodb_v07_path)
gecodb_v07.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,linker,is_pll,umlaut_applied,n2_lemma,n2_freq
comp_gecodb,,,,,,,,,,
gehölz_gürtel,Gehölzgürtel,30,gehölz,39384,31,_,False,False,gürtel,61060
zins_schwankung,Zinsschwankung,363,zins,487183,285,_,False,False,schwankung,60361
pfaffe_+n_bach,Pfaffenbach,2950,pfaffe,3221,32,_+n_,True,False,bach,485517
buch_institut,Buchinstitut,26,buch,2731652,603,_,False,False,institut,1066729
prunk_architektur,Prunkarchitektur,46,prunk,9475,69,_,False,False,architektur,224784
emission_+s_flut,Emissionsflut,265,emission,117056,121,_+s_,False,False,flut,162406
maske_+n_wechsel,Maskenwechsel,40,maske,253123,66,_+n_,True,False,wechsel,721192
dauer_klingel,Dauerklingel,158,dauer,456373,542,_,False,False,klingel,14125
beutel_buch,Beutelbuch,54,beutel,72185,25,_,False,False,buch,2731652
fuchs_kind,Fuchskind,49,fuchs,446696,81,_,False,False,kind,11283159

In [9]:
len(gecodb_v07)

277361

In [10]:
len(gecodb_v07["n1_lemma"].unique())

3593

In [11]:
# for L2P
len((gecodb_v07["n1_lemma"] + "+" + gecodb_v07["linker"]).unique())

4786

In [12]:
gecodb_v07["linker"].unique()

<StringArray>
[     '_',  '_+es_', '_+=er_',   '_+s_',  '_+er_',   '_+=_',   '_+e_',
   '_+n_',  '_+=e_',  '_+en_', '_+ens_',  '_+ns_']
Length: 12, dtype: str

#### SP18_Pl_Constr

In [13]:
sp18_pl_constr_path = "resources/developed/sp18/sp18_pl_constr.tsv"
sp18_pl_constr = load_sp18(sp18_pl_constr_path)
sp18_pl_constr.sample(10)

,n1,n2,n1_pl_marker,n1_sem,is_linker_pl,wc
gecodb,,,,,,
bett_vorleger,bett,vorleger,_+en_,ind,False,2382
haus_übergabe,haus,übergabe,_+=er_,ind,False,110
brief_auswahl,brief,auswahl,_+e_,coll,False,89
schloss_+=er_chef,schloss,chef,_+=er_,ind,True,307
hand_stab,hand,stab,_+=e_,ind,False,21
kind_+er_reise,kind,reise,_+er_,ind,True,222
apfel_duft,apfel,duft,_+=_,ind,False,158
schloss_+=er_landschaft,schloss,landschaft,_+=er_,konvc,True,299
weg_+e_pauschale,weg,pauschale,_+e_,ind,True,166
gerät_+e_kennung,gerät,kennung,_+e_,ind,True,82

In [14]:
len(sp18_pl_constr)

2681

In [15]:
len(sp18_pl_constr["n1"].unique())

44

In [22]:
# for n1+sem (pluralic constraints)
len((sp18_pl_constr["n1"] + "+" + (sp18_pl_constr["n1_sem"] == "ind").astype(str)).unique())

78

In [16]:
# for L2P
# n1_linker = lambda g: re.sub(r"_[^_]+$", "", g)
sp18_pl_constr["n1+linker"] = sp18_pl_constr.index.map(n1_linker)
len(sp18_pl_constr["n1+linker"].unique())

88

In [18]:
# linker = lambda n1l: "_" if not "_" in n1l else n1l.split("_")[1]
sp18_pl_constr["linker"] = sp18_pl_constr["n1+linker"].map(linker)
sp18_pl_constr["linker"].unique()

<StringArray>
['+=', '_', '+=er', '+=e', '+en', '+er', '+e', '+s', '+n']
Length: 9, dtype: str