### Small script to compute the size of the datasets for constraint verfication.

In [1]:
# make the root directory the pwd
%cd ..

/Users/maksimshmalts/Documents/DieKonstraintsPrivat/semrel_comp_corp_study-private

In [2]:
from data_utils.load_datasets import load_gecodb, load_sp18
from data_utils.gecodb_compound_parser import Compound

In [3]:
get_linker = lambda g: (
    "\"" if (l := Compound(g).linkers[0]).adds_umlaut else ""
) + l.morph

get_linker_gecodb = lambda g: "_" if len((s := g.split("_"))) == 2 else s[1]

#### GeCoDB_v06

In [4]:
gecodb_v06_path = "resources/comp_constr_corp_study_mar26/gecodb_v06.tsv"
gecodb_v06 = load_gecodb(gecodb_v06_path)
gecodb_v06.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,n1_mass_freq,n2_lemma,n2_freq
comp_gecodb,,,,,,,,
tanz_zelt,Tanzzelt,207,tanz,581106,435,608086,zelt,257843
stein_reichtum,Steinreichtum,38,stein,884861,510,832360,reichtum,116998
versicherung_+s_zentrale,Versicherungszentrale,84,versicherung,374128,249,264925,zentrale,158371
wahl_woche,Wahlwoche,271,wahl,2153643,479,1657474,woche,7759082
kirche_+n_patronin,Kirchenpatronin,190,kirche,2553981,530,1212964,patronin,3639
markt_übersättigung,Marktübersättigung,35,markt,2649376,657,1463426,übersättigung,2209
literatur_archiv,Literaturarchiv,5836,literatur,395247,268,231653,archiv,347470
herbst_forum,Herbstforum,142,herbst,1205048,311,242334,forum,388597
sprint_qualifikation,Sprintqualifikation,20,sprint,94159,64,28388,qualifikation,302318
vermarktung_+s_idee,Vermarktungsidee,428,vermarktung,118109,115,26293,idee,2322882

In [5]:
len(gecodb_v06)

282767

In [6]:
len(gecodb_v06["n1_lemma"].unique())

3613

In [7]:
# for L2P;
# since gecodb_v06 marks all linker allomorphs
# differently (e.g. _+n_ vs. _+en_), we first
# parse them into their morphs
gecodb_v06["linker"] = gecodb_v06.index.map(get_linker)
gecodb_v06["n1+linker"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker"]
len(gecodb_v06["n1+linker"].unique())

4868

In [8]:
# # DEPRECATED: produces the same result, which is explained
# # by the fact that _+en_ and _+n_ are distributed complementary;
# # `l2p:n` distinguishes between _+n_ and _+en_ so we will
# # calculate the items for it individually
# get_linker = lambda g: "_" if len((s := g.split("_"))) == 2 else s[1]
# gecodb_v06["linker_gecodb"] = gecodb_v06.index.map(get_linker)
# nlinker_comps = gecodb_v06[
#     (gecodb_v06["linker"] == "en") &
#     (gecodb_v06["linker_gecodb"] == "+n")
# ].index
# gecodb_v06.loc[nlinker_comps, "linker"] = "n"
# gecodb_v06["n1+linker"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker"]
# len(gecodb_v06["n1+linker"].unique())

In [9]:
gecodb_v06["linker"].unique()

<StringArray>
['', 'es', '"er', 's', '"', 'e', 'en', '"e', 'ens']
Length: 9, dtype: str

In [10]:
gecodb_v06["linker_gecodb"] = gecodb_v06.index.map(get_linker_gecodb)
gecodb_v06["linker_gecodb"].unique()

<StringArray>
['_', '+es', '+=er', '+s', '+=', '+e', '+n', '+=e', '+en', '+ens', '+ns']
Length: 11, dtype: str

#### GeCoDB_v07

In [11]:
gecodb_v07_path = "resources/developed/gecodb_v07.tsv"
gecodb_v07 = load_gecodb(gecodb_v07_path)
gecodb_v07.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,linker,is_pll,umlaut_applied,n2_lemma,n2_freq
comp_gecodb,,,,,,,,,,
traktor_+en_schlosser,Traktorenschlosser,471,traktor,183782,69,_+en_,True,False,schlosser,53653
lunch_tüte,Lunchtüte,42,lunch,13917,10,_,False,False,tüte,103256
kanal_röhre,Kanalröhre,142,kanal,254817,153,_,False,False,röhre,42307
frau_+en_ausstellung,Frauenausstellung,40,frau,9838661,607,_+en_,True,False,ausstellung,2116581
gast_kämpferin,Gastkämpferin,31,gast,4687625,464,_,False,False,kämpferin,16254
rücktritt_+s_frage,Rücktrittsfrage,126,rücktritt,388399,49,_+s_,False,False,frage,5961439
rest_vertrauen,Restvertrauen,150,rest,680849,270,_,False,False,vertrauen,638172
karpfen_museum,Karpfenmuseum,70,karpfen,38580,38,_,False,False,museum,1615048
tee_tasse,Teetasse,3374,tee,180981,165,_,False,False,tasse,109150
schiff_+s_heck,Schiffsheck,90,schiff,689036,372,_+s_,False,False,heck,91201

In [12]:
len(gecodb_v07)

277361

In [13]:
len(gecodb_v07["n1_lemma"].unique())

3593

In [14]:
# for L2P;
# since gecodb_v07 marks all linker allomorphs
# differently (e.g. _+n_ vs. _+en_), we first
# parse them into their morphs
gecodb_v07.rename(columns={"linker": "linker_gecodb"}, inplace=True)
gecodb_v07["linker"] = gecodb_v07.index.map(get_linker)
gecodb_v07["n1+linker"] = gecodb_v07["n1_lemma"] + "_" + gecodb_v07["linker"]
len(gecodb_v07["n1+linker"].unique())

4786

In [15]:
gecodb_v07["linker"].unique()

<StringArray>
['', 'es', '"er', 's', 'er', '"', 'e', 'en', '"e', 'ens']
Length: 10, dtype: str

In [16]:
gecodb_v07["linker_gecodb"].unique()

<StringArray>
[     '_',  '_+es_', '_+=er_',   '_+s_',  '_+er_',   '_+=_',   '_+e_',
   '_+n_',  '_+=e_',  '_+en_', '_+ens_',  '_+ns_']
Length: 12, dtype: str

#### SP18_Pl_Constr

In [17]:
sp18_pl_constr_path = "resources/developed/sp18/sp18_pl_constr.tsv"
sp18_pl_constr = load_sp18(sp18_pl_constr_path)
sp18_pl_constr.sample(10)

                        n1         n2 n1_pl_marker n1_sem  is_linker_pl     wc
gecodb
gerät_+e_steuerung   gerät  steuerung         _+e_    ind          True     45
rad_schraube           rad   schraube       _+=er_    ind         False    362
brett_+er_wand       brett       wand        _+er_    ind          True   1731
buch_branche          buch    branche       _+=er_    ind         False   5456
katze_+n_körbchen    katze   körbchen         _+n_    ind          True    143
bild_material         bild   material        _+er_    ind         False  13966
bild_+er_collage      bild    collage        _+er_   coll          True    225
vogel_predigt        vogel    predigt         _+=_    ind         False    209
person_+en_kartei   person     kartei        _+en_   coll          True     97
bild_sprache          bild    sprache        _+er_    ind         False  13916

In [18]:
len(sp18_pl_constr)

2681

In [19]:
len(sp18_pl_constr["n1"].unique())

44

In [20]:
# for n1+sem (pluralic constraints)
len((sp18_pl_constr["n1"] + "+" + (sp18_pl_constr["n1_sem"] == "ind").astype(str)).unique())

78

In [21]:
# for L2P
# since sp18_pl_constr marks all linker allomorphs
# differently (e.g. _+n_ vs. _+en_), we first
# parse them into their morphs
sp18_pl_constr["linker"] = sp18_pl_constr.index.map(get_linker)
sp18_pl_constr["n1+linker"] = sp18_pl_constr["n1"] + "_" + sp18_pl_constr["linker"]
len(sp18_pl_constr["n1+linker"].unique())

88

In [23]:
sp18_pl_constr["linker"].unique()

<StringArray>
['"', '', '"er', '"e', 'en', 'er', 'e', 's']
Length: 8, dtype: str

In [22]:
# linker = lambda n1l: "_" if not "_" in n1l else n1l.split("_")[1]
sp18_pl_constr["linker_gecodb"] = sp18_pl_constr.index.map(get_linker_gecodb)
sp18_pl_constr["linker_gecodb"].unique()

<StringArray>
['+=', '_', '+=er', '+=e', '+en', '+er', '+e', '+s', '+n']
Length: 9, dtype: str