### Small script to compute the size of the datasets for constraint verfication.

In [2]:
# make the root directory the pwd
%cd ..

/Users/maxschmaltz/Documents/DieKonstraintsPrivat/semrel_comp_corp_study-private

In [3]:
from data_utils.load_datasets import load_gecodb, load_sp18
from data_utils.gecodb_compound_parser import Compound

In [4]:
get_linker_gecodb = lambda g: "_" if len((s := g.split("_"))) == 2 else s[1]

get_linker = lambda g: (
    "\"" if (l := Compound(g).linkers[0]).adds_umlaut else ""
) + l.morph

#### GeCoDB_v06

In [5]:
gecodb_v06_path = "resources/comp_constr_corp_study_mar26/gecodb_v06.tsv"
gecodb_v06 = load_gecodb(gecodb_v06_path)
gecodb_v06.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,n1_mass_freq,n2_lemma,n2_freq
comp_gecodb,,,,,,,,
mitwirkung_+s_gesetz,Mitwirkungsgesetz,41,mitwirkung,77892,19,12797,gesetz,1456035
keim_herd,Keimherd,43,keim,73423,60,34319,herd,81152
wein_rechnung,Weinrechnung,58,wein,656636,570,913875,rechnung,554471
karte_+n_vertrieb,Kartenvertrieb,109,karte,1723659,235,225153,vertrieb,137537
rasen_narbe,Rasennarbe,97,rasen,258340,134,139635,narbe,38486
prunk_schwert,Prunkschwert,70,prunk,9475,69,62259,schwert,77533
schluck_vermögen,Schluckvermögen,90,schluck,50912,15,9002,vermögen,303807
opium_pflanze,Opiumpflanze,23,opium,9436,30,3942,pflanze,123858
falke_+n_brunnen,Falkenbrunnen,94,falke,78962,63,52610,brunnen,201789
regierung_+s_feind,Regierungsfeind,21,regierung,2648830,439,1476340,feind,251836

In [6]:
gecodb_v06["linker_gecodb"] = gecodb_v06.index.map(get_linker_gecodb)
gecodb_v06["linker"] = gecodb_v06.index.map(get_linker)

In [7]:
len(gecodb_v06)

282767

In [8]:
len(gecodb_v06["n1_lemma"].unique())

3614

In [9]:
# for L2P
# note that, even though gecodb_v06 distinguishes between linker allomorphs,
# (e.g. _+n_ vs. _+en_), the number of N1+linker is the same on practive
# no matter whether we count N1+(linker morph) or N1+(linker allomorph);
# this is explained by the fact that the allomorphs are distributed
# complementarily, and there are no cases documented in which one N1 may attach
# two allomorphs of the same linker in different compounds
gecodb_v06["n1+linker"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker"]
gecodb_v06["n1+linker_gecodb"] = gecodb_v06["n1_lemma"] + "_" + gecodb_v06["linker_gecodb"]
len(gecodb_v06["n1+linker"].unique()), len(gecodb_v06["n1+linker_gecodb"].unique())

(4870, 4870)

In [10]:
gecodb_v06["linker"].unique()

<ArrowStringArray>
['', 'es', '"er', 's', '"', 'e', 'en', '"e', 'ens']
Length: 9, dtype: str

In [11]:
gecodb_v06["linker_gecodb"].unique()

<ArrowStringArray>
['_', '+es', '+=er', '+s', '+=', '+e', '+n', '+=e', '+en', '+ens', '+ns']
Length: 11, dtype: str

#### GeCoDB_v07

In [12]:
gecodb_v07_path = "resources/developed/gecodb_v07.tsv"
gecodb_v07 = load_gecodb(gecodb_v07_path)
gecodb_v07.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,linker,is_pll,umlaut_applied,n2_lemma,n2_freq
comp_gecodb,,,,,,,,,,
seite_+n_halle,Seitenhalle,69,seite,5630195,254,_+n_,True,False,halle,2009119
rheuma_kissen,Rheumakissen,20,rheuma,17198,27,_,False,False,kissen,49709
ziel_stärke,Zielstärke,48,ziel,3512621,292,_,False,False,stärke,338309
entstehung_+s_seite,Entstehungsseite,36,entstehung,124785,31,_+s_,False,False,seite,5630195
flocke_+n_blume,Flockenblume,539,flocke,20513,19,_+n_,True,False,blume,390102
ball_besitz,Ballbesitz,43729,ball,1195425,226,_,False,False,besitz,304879
unfall_analytiker,Unfallanalytiker,162,unfall,1264412,191,_,False,False,analytiker,11919
ermittlung_+s_fortschritt,Ermittlungsfortschritt,79,ermittlung,805725,117,_+s_,False,False,fortschritt,436380
stamm_urlauber,Stammurlauber,55,stamm,196839,329,_,False,False,urlauber,222832
blick_winkel,Blickwinkel,60094,blick,2776172,43,_,False,False,winkel,173196

In [13]:
gecodb_v07["linker_gecodb"] = gecodb_v07["linker"].copy()
gecodb_v07["linker"] = gecodb_v07.index.map(get_linker)

In [14]:
len(gecodb_v07)

275409

In [15]:
len(gecodb_v07["n1_lemma"].unique())

3594

In [16]:
# for L2P;
gecodb_v07["n1+linker"] = gecodb_v07["n1_lemma"] + "_" + gecodb_v07["linker"]
gecodb_v07["n1+linker_gecodb"] = gecodb_v07["n1_lemma"] + "_" + gecodb_v07["linker_gecodb"]
len(gecodb_v07["n1+linker"].unique()), len(gecodb_v07["n1+linker_gecodb"].unique())

(4743, 4743)

In [17]:
gecodb_v07["linker"].unique()

<ArrowStringArray>
['', 'es', '"er', 's', 'er', '"', 'e', 'en', '"e', 'ens']
Length: 10, dtype: str

In [18]:
gecodb_v07["linker_gecodb"].unique()

<ArrowStringArray>
[     '_',  '_+es_', '_+=er_',   '_+s_',  '_+er_',   '_+=_',   '_+e_',
   '_+n_',  '_+=e_',  '_+en_', '_+ens_',  '_+ns_']
Length: 12, dtype: str

#### GeCoDB_v07_GN

In [19]:
gecodb_v07_gn_path = "resources/developed/gecodb_v07_gn.tsv"
gecodb_v07_gn = load_gecodb(gecodb_v07_gn_path)
gecodb_v07_gn.sample(10)

,comp_lemma,comp_freq,n1_lemma,n1_freq,n1_prod,linker,is_pll,umlaut_applied,n2_lemma,n2_freq
comp_gecodb,,,,,,,,,,
einzug_+s_bereich,Einzugsbereich,22719,einzug,307478,29,_+s_,False,False,bereich,3022379
pappel_blatt,Pappelblatt,80,pappel,27165,25,_,False,False,blatt,474851
bildung_+s_hintergrund,Bildungshintergrund,1077,bildung,791479,541,_+s_,False,False,hintergrund,1167724
verkehr_+s_kreisel,Verkehrskreisel,4695,verkehr,875083,583,_+s_,False,False,kreisel,94850
widerspruch_+s_frist,Widerspruchsfrist,2071,widerspruch,383679,35,_+s_,False,False,frist,233867
gruppe_+n_flug,Gruppenflug,81,gruppe,2849144,358,_+n_,True,False,flug,410864
puppe_+n_wiege,Puppenwiege,191,puppe,130526,137,_+n_,True,False,wiege,54200
getränk_+e_abteilung,Getränkeabteilung,557,getränk,422887,155,_+e_,True,False,abteilung,461021
preis_änderung,Preisänderung,5572,preis,2708828,503,_,False,False,änderung,718386
lizenz_einnahme,Lizenzeinnahme,1791,lizenz,128811,140,_,False,False,einnahme,595736

In [20]:
gecodb_v07_gn["linker_gecodb"] = gecodb_v07_gn["linker"].copy()
gecodb_v07_gn["linker"] = gecodb_v07_gn.index.map(get_linker)

In [21]:
len(gecodb_v07_gn)

52433

In [22]:
len(gecodb_v07_gn["n1_lemma"].unique())

3334

In [34]:
# for N1+N2
len((gecodb_v07_gn["n1_lemma"] + "+" + gecodb_v07_gn["n2_lemma"]).unique())

52076

In [23]:
# for L2P;
gecodb_v07_gn["n1+linker"] = gecodb_v07_gn["n1_lemma"] + "_" + gecodb_v07_gn["linker"]
gecodb_v07_gn["n1+linker_gecodb"] = gecodb_v07_gn["n1_lemma"] + "_" + gecodb_v07_gn["linker_gecodb"]
len(gecodb_v07_gn["n1+linker"].unique()), len(gecodb_v07_gn["n1+linker_gecodb"].unique())

(3623, 3623)

In [24]:
gecodb_v07_gn["linker"].unique()

<ArrowStringArray>
['', 'es', '"er', 's', 'er', 'e', 'en', '"e', 'ens', '"']
Length: 10, dtype: str

In [25]:
gecodb_v07_gn["linker_gecodb"].unique()

<ArrowStringArray>
[     '_',  '_+es_', '_+=er_',   '_+s_',  '_+er_',   '_+e_',   '_+n_',
  '_+=e_',  '_+en_', '_+ens_',  '_+ns_',   '_+=_']
Length: 12, dtype: str

#### SP18_Pl_Constr

In [26]:
sp18_pl_constr_path = "resources/developed/sp18/sp18_pl_constr.tsv"
sp18_pl_constr = load_sp18(sp18_pl_constr_path)
sp18_pl_constr.sample(10)

,n1,n2,n1_pl_marker,n1_sem,is_linker_pl,wc
gecodb,,,,,,
hand_pumpe,hand,pumpe,_+=e_,ind,False,1290
ohr_+en_stellung,ohr,stellung,_+en_,ind,True,25
geschenk_+e_stand,geschenk,stand,_+e_,ind,True,64
geschenk_+e_finder,geschenk,finder,_+e_,ind,True,42
kind_+er_stube,kind,stube,_+er_,ind,True,11400
apfel_kern,apfel,kern,_+=_,ind,False,902
rad_verleih,rad,verleih,_+=er_,ind,False,788
lied_folge,lied,folge,_+er_,coll,False,432
brief_umschlag,brief,umschlag,_+e_,ind,False,13711
bad_+=er_abteilung,bad,abteilung,_+=er_,ind,True,523

In [27]:
len(sp18_pl_constr)

2304

In [28]:
len(sp18_pl_constr["n1"].unique())

43

In [29]:
# for n1+sem (pluralic constraints)
len((sp18_pl_constr["n1"] + "+" + (sp18_pl_constr["n1_sem"] == "ind").astype(str)).unique())

77

In [30]:
# for L2P
# since sp18_pl_constr marks all linker allomorphs
# differently (e.g. _+n_ vs. _+en_), we first
# parse them into their morphs
sp18_pl_constr["linker"] = sp18_pl_constr.index.map(get_linker)
sp18_pl_constr["n1+linker"] = sp18_pl_constr["n1"] + "_" + sp18_pl_constr["linker"]
len(sp18_pl_constr["n1+linker"].unique())

86

In [31]:
sp18_pl_constr["linker"].unique()

<ArrowStringArray>
['"', '', '"er', '"e', 'en', 'er', 'e', 's']
Length: 8, dtype: str

In [32]:
# linker = lambda n1l: "_" if not "_" in n1l else n1l.split("_")[1]
sp18_pl_constr["linker_gecodb"] = sp18_pl_constr.index.map(get_linker_gecodb)
sp18_pl_constr["linker_gecodb"].unique()

<ArrowStringArray>
['+=', '_', '+=er', '+=e', '+en', '+er', '+e', '+s', '+n']
Length: 9, dtype: str