In [1]:
import os
import pandas as pd
from collections import defaultdict

In [2]:
sp18 = pd.read_csv(
    "../resources/developed/sp18/sp18.tsv",
    sep="\t",
    header=0,
    index_col="gecodb",
    dtype=defaultdict(
        lambda: str,
        wc="int",
        is_linker_pl="bool"
    ),
    # = csv.QUOTE_NONE, separate by tabs only
    quoting=3
)

sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_achtel,apfel,achtel,_+=_,ind,pl,True,0,"Eiweiß dazugeben , Mandeln und Speißestärke un...",39d711a8-b8f0-40a4-ae07-515d675186f4
apfel_+=_allergie,apfel,allergie,_+=_,ind,sg,True,0,"In der Symptomsprache , nach der die Kreative ...",00d6a774-fbeb-450e-884b-39603425682b
apfel_+=_annahme,apfel,annahme,_+=_,ind,sg,True,0,Die Kapsel mit vielen Dokumenten wird vom Klem...,09ee64bd-555b-4784-89e3-de1e84dd0eb1
apfel_+=_anzahl,apfel,anzahl,_+=_,coll,sg,True,0,"Schaut gut aus , aber sind halt auch nur einfa...",c0c20966-15d5-4d49-aa09-da0d840148c1
apfel_+=_ausstellung,apfel,ausstellung,_+=_,konvc,sg,True,0,Wiederum für viele sehr interessant waren die ...,0a37e563-e6f4-4d3b-967a-5520008f5f6f
...,...,...,...,...,...,...,...,...,...
zitat_zutraulichkeit,zitat,zutraulichkeit,_+e_,ind,sg,False,0,"""Wenn also insinuiert wird , daß die vulgär-dr...",96b3d000-bf76-4013-b0b9-e9e16e6f5eb6
zitat_zweck,zitat,zweck,_+e_,ind,pl,False,3,"Ein rechtmäßiger Zitatzweck liegt nur vor , we...",e5c5c0b1-a0d2-412d-b42b-e59439baeca4
zitat_zweck,zitat,zweck,_+e_,ind,sg,False,3,Die Rechte des Urhebers werden durch die in § ...,b82478cb-786e-4e81-9eef-356e521c39f4
zitat_zweck,zitat,zweck,_+e_,ind,sg,False,3,Zitate aus noch unveröffentlichten Filmen sind...,fd5ba797-42fc-4a1e-b690-394a53e58d3b
zitat_überschrift,zitat,überschrift,_+e_,ind,sg,False,0,"""Hoffentlich passieren da nicht solche Dinge w...",b7d8c91e-85e6-40a0-a028-a84e9516418c

In [3]:
sp18 = sp18[~sp18.index.duplicated(keep="first")]
sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_achtel,apfel,achtel,_+=_,ind,pl,True,0,"Eiweiß dazugeben , Mandeln und Speißestärke un...",39d711a8-b8f0-40a4-ae07-515d675186f4
apfel_+=_allergie,apfel,allergie,_+=_,ind,sg,True,0,"In der Symptomsprache , nach der die Kreative ...",00d6a774-fbeb-450e-884b-39603425682b
apfel_+=_annahme,apfel,annahme,_+=_,ind,sg,True,0,Die Kapsel mit vielen Dokumenten wird vom Klem...,09ee64bd-555b-4784-89e3-de1e84dd0eb1
apfel_+=_anzahl,apfel,anzahl,_+=_,coll,sg,True,0,"Schaut gut aus , aber sind halt auch nur einfa...",c0c20966-15d5-4d49-aa09-da0d840148c1
apfel_+=_ausstellung,apfel,ausstellung,_+=_,konvc,sg,True,0,Wiederum für viele sehr interessant waren die ...,0a37e563-e6f4-4d3b-967a-5520008f5f6f
...,...,...,...,...,...,...,...,...,...
zitat_zusammenfassung,zitat,zusammenfassung,_+e_,ind,sg,False,0,"Zweitens kannst du dann wohl sicher sagen , da...",18d6a5f6-9d07-4b3c-a8b9-f766fc8301c3
zitat_zusammenstellung,zitat,zusammenstellung,_+e_,coll,pl,False,0,Ich lese diese Antworten nur selten . Aber wen...,891d1c31-9385-4a45-87c1-faac7e466668
zitat_zutraulichkeit,zitat,zutraulichkeit,_+e_,ind,sg,False,0,"""Wenn also insinuiert wird , daß die vulgär-dr...",96b3d000-bf76-4013-b0b9-e9e16e6f5eb6
zitat_zweck,zitat,zweck,_+e_,ind,pl,False,3,"Ein rechtmäßiger Zitatzweck liegt nur vor , we...",e5c5c0b1-a0d2-412d-b42b-e59439baeca4
zitat_überschrift,zitat,überschrift,_+e_,ind,sg,False,0,"""Hoffentlich passieren da nicht solche Dinge w...",b7d8c91e-85e6-40a0-a028-a84e9516418c

In [4]:
sp18 = sp18[sp18["wc"] >= 20]
sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_baum,apfel,baum,_+=_,ind,pl,True,122,An einem kleinem Flüsschen wandern wir bis sic...,578ee7e1-76f2-471b-b957-64a60b8cb33f
apfel_+=_säure,apfel,säure,_+=_,ind,pl,True,44,Säurearme Kaffeesorten werden meist weniger gu...,c6d4244b-4315-4cb5-a8c9-a937289c38d5
apfel_+=_wein,apfel,wein,_+=_,ind,sg,True,45,"""Wer diesen Titel erhält , darf zudem ein Jahr...",332458d8-cfeb-4983-8348-23fb4c318e43
apfel_bauer,apfel,bauer,_+=_,ind,sg,False,832,"""Bei schönstem Sonnenschein nimmt Hannes Pante...",9648573d-340f-484d-b991-55bfa2c86491
apfel_baum,apfel,baum,_+=_,ind,sg,False,27287,"""Zuweilen gibt es aber auch romantische Moment...",beddee9e-5790-4111-b893-7d00663e92ae
...,...,...,...,...,...,...,...,...,...
zitat_+e_sammlung,zitat,sammlung,_+e_,konvc,pl,True,92,"Nun ja , inzwischen haben auch Fachleute ganze...",23569f32-4e02-4c50-b4cb-7230df8639da
zitat_kunst,zitat,kunst,_+e_,ind,sg,False,21,"In Einschätzung des Gegenstands , von dem wir ...",df989c83-8cfb-4da6-bae1-154e7b7b9b27
zitat_montage,zitat,montage,_+e_,konvc,sg,False,59,"Das erste ist ein 1961 erschienener , populär ...",2ab481f5-d511-48f0-b3b8-3ea59421a58e
zitat_recht,zitat,recht,_+e_,ind,pl,False,168,"""So sehr Rechtssicherheit und Gleichheit vor d...",b532b79d-3559-410b-a3c4-e5d3bd4d16e8
zitat_spender,zitat,spender,_+e_,ind,sg,False,39,"Danke , das Kompliment erwidere ich gern . Mus...",49849022-b813-4851-bd7c-cc1486071e17

In [5]:
sp18[(sp18["n1"] == "apfel") & (sp18["n2"] == "baum")]

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_baum,apfel,baum,_+=_,ind,pl,True,122,An einem kleinem Flüsschen wandern wir bis sic...,578ee7e1-76f2-471b-b957-64a60b8cb33f
apfel_baum,apfel,baum,_+=_,ind,sg,False,27287,"""Zuweilen gibt es aber auch romantische Moment...",beddee9e-5790-4111-b893-7d00663e92ae

In [6]:
sp18 = sp18[["n1_pl_marker", "n1_sem", "is_linker_pl"]]
sp18

                  n1_pl_marker n1_sem  is_linker_pl
gecodb
apfel_+=_baum             _+=_    ind          True
apfel_+=_säure            _+=_    ind          True
apfel_+=_wein             _+=_    ind          True
apfel_bauer               _+=_    ind         False
apfel_baum                _+=_    ind         False
...                        ...    ...           ...
zitat_+e_sammlung         _+e_  konvc          True
zitat_kunst               _+e_    ind         False
zitat_montage             _+e_  konvc         False
zitat_recht               _+e_    ind         False
zitat_spender             _+e_    ind         False

[2681 rows x 3 columns]

In [7]:
# p2l:decl_cl:pl:#e-0|pl_interpr-e
#
# First constituents that are constituted by nouns that build
# the plural form with -e attach -e- irregularly in compounds
# in which the second constituent forces
# a plural meaning of the given first constituent.
def plur_e_pl_is_applicable(row: pd.Series, strict=True) -> bool:
	cond = ["coll"] if strict else ["coll", "konvc"]
	return (
		# morph cond
		(row["n1_pl_marker"] == "_+e_") and
        # sem cond
        row["n1_sem"] in cond
    )

def plur_e_pl_applies(row: pd.Series, strict=True) -> bool:
    return row["is_linker_pl"]


# p2l:decl_cl:pl:#er-0/er|!pl_interpr-0
#
# First constituents that are constituted by nouns that build
# the plural form with -(")er
# attach a zero linker in majority of compounds
# in which the second constituent forces
# a singular meaning of the given first constituent.
def plur_er_sg_is_applicable(row: pd.Series, strict=True) -> bool:
	return (
		# morph cond
		(row["n1_pl_marker"] in ["_+er_", "_+=er_"]) and
        # sem cond
        row["n1_sem"] == "ind"
    )

def plur_er_sg_applies(row: pd.Series, strict=True) -> bool:
    return not row["is_linker_pl"]


# p2l:decl_cl:pl:#er-0/er|pl_interpr-er
#
# First constituents that are constituted by nouns that build
# the plural form with -(")er
# attach -(")er- more likely in compounds
# in which the second constituent forces
# a plural meaning of the given first constituent.
def plur_er_pl_is_applicable(row: pd.Series, strict=True) -> bool:
	cond = ["coll"] if strict else ["coll", "konvc"]
	return (
		# morph cond
		(row["n1_pl_marker"] in ["_+er_", "_+=er_"]) and
        # sem cond
        row["n1_sem"] in cond
    )

def plur_er_pl_applies(row: pd.Series, strict=True) -> bool:
    return row["is_linker_pl"]


# p2l:decl_cl:pl:#e_uml-0|pl_interpr-e_uml
#
# First constituents that are constituted by nouns that build
# the plural form with -e and umlaut attach -"e- irregularly in compounds
# in which the second constituent forces
# a plural meaning of the given first constituent.
def plur_e_uml_pl_is_applicable(row: pd.Series, strict=True) -> bool:
	cond = ["coll"] if strict else ["coll", "konvc"]
	return (
		# morph cond
		(row["n1_pl_marker"] == "_+=e_") and
        # sem cond
        row["n1_sem"] in cond
    )

def plur_e_uml_pl_applies(row: pd.Series, strict=True) -> bool:
    return row["is_linker_pl"]


# p2l:decl_cl:pl:#0_uml-0|pl_interpr-0_uml
#
# First constituents that are constituted by nouns that build
# the plural form with a zero ending and umlaut attach
# a zero linker with umlaut irregularly in compounds
# in which the second constituent forces
# a plural meaning of the given first constituent.
def plur_0_uml_pl_is_applicable(row: pd.Series, strict=True) -> bool:
	cond = ["coll"] if strict else ["coll", "konvc"]
	return (
		# morph cond
		(row["n1_pl_marker"] == "_+=_") and
        # sem cond
        row["n1_sem"] in cond
    )

def plur_0_uml_pl_applies(row: pd.Series, strict=True) -> bool:
    return row["is_linker_pl"]



# p2l:tend:pl_interpr-pl_marker|def-pl_marker
#
# Linkers that are identical to the plural ending
# of the first constituent in a given compound
# tend to be associated with
# a plural meaning of this first constituent within the compound.
def pl_interpr_is_applicable(row: pd.Series, strict=True) -> bool:
	return row["is_linker_pl"]

def pl_interpr_applies(row: pd.Series, strict=True) -> bool:
	cond = ["coll"] if strict else ["coll", "konvc"]
	return row["n1_sem"] in cond

In [8]:
n = len(sp18)
stats = {}
for id, func_is_a, func_a in [
    ("plur_e_pl", plur_e_pl_is_applicable, plur_e_pl_applies),
    ("plur_er_sg", plur_er_sg_is_applicable, plur_er_sg_applies),
    ("plur_er_pl", plur_er_pl_is_applicable, plur_er_pl_applies),
    ("plur_e_uml_pl", plur_e_uml_pl_is_applicable, plur_e_uml_pl_applies),
    ("plur_0_uml_pl", plur_0_uml_pl_is_applicable, plur_0_uml_pl_applies),
    ("pl_interpr", pl_interpr_is_applicable, pl_interpr_applies)
]:
    for strict in [True, False]:
        apply = lambda row: (
            (is_applicable := func_is_a(row, strict)),
            func_a(row, strict) if is_applicable else False
        )
        strict_str = "strict" if strict else "lax"
        sp18[f"{id}_is_applicable_{strict_str}"], sp18[f"{id}_applies_{strict_str}"] = zip(
            *sp18.apply(apply, axis=1)
        )
        cvg_abs = len(sp18[sp18[f"{id}_is_applicable_{strict_str}"]])
        reg_abs = len(sp18[sp18[f"{id}_applies_{strict_str}"]])
        stats[(id, strict_str)] = {
            "cvg": cvg_abs / n,
            "reg": reg_abs / cvg_abs
        }

In [9]:
stats_df = pd.DataFrame(stats).T.sort_index(ascending=False)
stats_df

                           cvg       reg
plur_er_sg    strict  0.312570  0.609785
              lax     0.312570  0.609785
plur_er_pl    strict  0.037673  0.732673
              lax     0.056695  0.796053
plur_e_uml_pl strict  0.009325  0.880000
              lax     0.010817  0.896552
plur_e_pl     strict  0.020888  0.535714
              lax     0.028721  0.545455
plur_0_uml_pl strict  0.007460  0.650000
              lax     0.010817  0.620690
pl_interpr    strict  0.469228  0.155803
              lax     0.469228  0.221781

In [12]:
sp18[
    sp18["plur_0_uml_pl_is_applicable_strict"] &
    ~sp18["plur_0_uml_pl_applies_strict"]
]

,n1_pl_marker,n1_sem,is_linker_pl,plur_e_pl_is_applicable_strict,plur_e_pl_applies_strict,plur_e_pl_is_applicable_lax,plur_e_pl_applies_lax,plur_er_sg_is_applicable_strict,plur_er_sg_applies_strict,plur_er_sg_is_applicable_lax,...,plur_e_uml_pl_is_applicable_lax,plur_e_uml_pl_applies_lax,plur_0_uml_pl_is_applicable_strict,plur_0_uml_pl_applies_strict,plur_0_uml_pl_is_applicable_lax,plur_0_uml_pl_applies_lax,pl_interpr_is_applicable_strict,pl_interpr_applies_strict,pl_interpr_is_applicable_lax,pl_interpr_applies_lax
gecodb,,,,,,,,,,,,,,,,,,,,,
vogel_gruppe,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_paar,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_population,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_reichtum,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_schar,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_schwarm,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
vogel_zug,_+=_,coll,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False